[project]
name = "scrape-test"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "crawlee[all]>=0.5.2",
    "markdownify>=0.14.1",
    "markitdown>=0.0.1a3",
    "numpy>=2.2.2",
]
